steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - $_BACKEND_IMAGE
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_BACKEND_IMAGE

images:
  - $_BACKEND_IMAGE
options:
  logging: CLOUD_LOGGING_ONLY
